server:
  servlet:
    context-path: /geekshop

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: root
  jpa:
    show-sql: true
  thymeleaf:
    cache: false